import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/src/assets/globals.css";

export const metadata: Metadata = {
  title: "WisataDandy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-tertiary">{children}</body>
    </html>
  );
}
